// Seed tabel `places` dari dataset Google Maps (seeds/tegal-fnb.csv).
// Dipanggil via `npm run db:seed:places` — script ini hanya MENULISKAN
// file seed-places.sql; eksekusi ke D1 tetap lewat wrangler d1 execute.
// Pemilihan kolom & derivasi `city` mengikuti bentuk data yang dipakai
// halaman Explorer (lihat frontend/src/explorer/types.ts).
//
// Baris lokasi Jakarta dari hasil scrape DIBUANG: app ini untuk saran
// di area Tegal, titik Jakarta (~230 km) merusak fitBounds peta dan
// membingungkan pengguna.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Papa from "papaparse";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const csvPath = path.join(scriptDir, "..", "seeds", "tegal-fnb.csv");
const outPath = path.join(scriptDir, "..", "seed-places.sql");

// Wilayah dari address — nilai "city" dipakai filter wilayah di Explorer.
function deriveCity(address) {
  const a = (address || "").toLowerCase();
  const jakartaDistrict = a.match(/jakarta\s+(barat|pusat|selatan|timur|utara)/);
  if (jakartaDistrict) {
    const d = jakartaDistrict[1];
    return `Kota Jakarta ${d[0].toUpperCase()}${d.slice(1)}`;
  }
  if (a.includes("jakarta")) return "Jakarta";
  if (a.includes("brebes")) return "Kabupaten Brebes";
  if (/kabupaten tegal|tegal regency/.test(a)) return "Kabupaten Tegal";
  return "Kota Tegal";
}

function sqlStr(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function jsonOrNull(value) {
  if (!value || value === "null") return null;
  return value; // sudah berbentuk JSON valid dari ekspor
}

const csv = fs.readFileSync(csvPath, "utf8");
const { data, errors } = Papa.parse(csv, { header: true, skipEmptyLines: true });
if (errors.length > 0) {
  console.error("Parse errors:", errors.slice(0, 5));
  process.exit(1);
}

const rows = [];
let skippedJakarta = 0;
for (const r of data) {
  if (!r.cid || !r.title || !r.latitude || !r.longitude) continue; // baris tanpa koordinat tidak berguna untuk peta
  const city = deriveCity(r.address);
  if (city.toLowerCase().includes("jakarta")) {
    skippedJakarta++;
    continue;
  }
  rows.push(
    [
      sqlStr(r.cid),
      sqlStr(r.title),
      sqlStr(r.category),
      sqlStr(r.address || null),
      sqlStr(city),
      sqlStr(r.review_rating ? Number(r.review_rating) : null),
      String(Number(r.review_count) || 0),
      sqlStr(r.price_range || null),
      sqlStr(r.phone || null),
      sqlStr(r.website || null),
      sqlStr(r.thumbnail || null),
      String(Number(r.latitude)),
      String(Number(r.longitude)),
      sqlStr(r.link || null),
      sqlStr(r.street_view_url || null),
      sqlStr(r.plus_code || null),
      sqlStr(jsonOrNull(r.open_hours)),
      sqlStr(jsonOrNull(r.popular_times)),
      sqlStr(jsonOrNull(r.images)),
      sqlStr(jsonOrNull(r.about)),
      sqlStr(jsonOrNull(r.user_reviews)),
      sqlStr(jsonOrNull(r.reviews_per_rating)),
    ].join(", ")
  );
}

const statements = rows
  .map(
    (vals) => `INSERT OR REPLACE INTO places (
  id, title, category, address, city, rating, review_count, price_range,
  phone, website, thumbnail, latitude, longitude, link, street_view_url,
  plus_code, open_hours, popular_times, images, about, user_reviews, reviews_per_rating
) VALUES (
  ${vals}
);`
  )
  .join("\n\n");

fs.writeFileSync(
  outPath,
  // Hapus sisa seed lama baris Jakarta supaya re-seed bersih (INSERT OR
  // REPLACE hanya menimpa baris yang masih ada di CSV).
  `-- Generated by scripts/seed-places.mjs dari seeds/tegal-fnb.csv (${rows.length} places, ${skippedJakarta} baris Jakarta dibuang). Jangan edit manual.\n\nDELETE FROM places WHERE city LIKE '%Jakarta%';\n\n${statements}\n`
);
console.log(
  `OK: ${rows.length} places -> ${outPath} (${skippedJakarta} baris Jakarta dilewati)`
);
